### ISSUE TITLE
[FIXED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [sc0ty/grip#1]
Dear Mike,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sc0ty** [comment]
Sorry, no support for windows. I was heavy using POSIX interface, and Windows is not POSIX-compatible.
You could try to build it under Cygwin, or with Windows 10 bash.

**Comment by sc0ty** [comment]
Hey if you're still interested, I've ported grip to Windows. There are binaries in the releases page.

**Comment by sergeevabc** [comment]
Thank you for letting me know, @sc0ty.

**Comment by tex** [comment]
Thanks for Windows binaries!

I tried to cross compile it with mingww64 myself but failed (on NixOs, long story...) because of pthread.
On NixOs they do not have proper mingww64-pthreads, just the win32 that does not provide -lpthread.

**Comment by sc0ty** [comment]
It should work with whatever implementation of std::thread your compiler support, except grip-verify which is just for testing (I should probably rewrite it to use std::thread). Probably you just need to adjust GEN_CXXFLAGS and GEN_LDFLAGS  in src/gripgen/gripgen.mk

If you will still have problem with it, please create new issue, since this is not related to Windows binaries.
